# Generated by Django 4.0.8 on 2022-11-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField()),
                ('club_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='club_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_det_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_id', models.IntegerField()),
                ('comment', models.CharField(max_length=25)),
                ('student_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.BigIntegerField()),
                ('description_event', models.CharField(max_length=40)),
                ('club_name', models.CharField(max_length=15)),
                ('event_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.IntegerField()),
                ('task_name', models.CharField(max_length=25)),
                ('assignee', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=50)),
                ('current_date', models.DateField()),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('year', models.CharField(max_length=10)),
                ('roll', models.BigIntegerField()),
            ],
        ),
    ]
