# Generated by Django 4.0.8 on 2022-11-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='postv',
            field=models.IntegerField(default=0),
        ),
    ]
