# Generated by Django 4.0.8 on 2022-11-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_student_postv'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='clubsinterested',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
    ]
