# Generated by Django 4.0.8 on 2022-12-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_student_clubsinterested'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='volunteers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description_event',
            field=models.CharField(max_length=40000),
        ),
    ]
