# Generated by Django 4.0.8 on 2022-12-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_event_volunteers_alter_event_description_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2019-01-01'),
        ),
    ]
