# Generated by Django 4.0.8 on 2022-12-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_club_club_description_club_club_head_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=0),
        ),
    ]
